#!/bin/sh
# enables mesos logging, otherwise stdout goes to LOG_DIR
#LOGS=/var/log/mesos
# both master and slave will log into syslog file
USE_SYSLOG=false
# separate 'master.log' and 'slave.log' files
LOG_DIR="/var/log/mesos"
ULIMIT="-n 8192"
